import { StyleSheet } from "react-native";
import { Colors, Fonts } from "../../config/theme";
import metrix from "../../config/metrix";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.White,
    alignSelf: "center",
    shadowColor: "#000000",
    flexDirection: "row",
    shadowOpacity: 0.26,
    shadowOffset: { width: 0, height: 2 },
    justifyContent: "space-evenly",
    alignItems: "center",
    shadowRadius: 10,
    position: "absolute",
    bottom: 0,
    borderTopLeftRadius: metrix.VerticalSize(25),
    borderTopRightRadius: metrix.VerticalSize(25),
    height: metrix.VerticalSize(60),
    width: metrix.HorizontalSize(),
    elevation: 10,
  },
  box: {
    width: metrix.HorizontalSize(300),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: metrix.VerticalSize(20),
    // bottom: metrix.VerticalSize(90),
    // height: metrix.VerticalSize(250),
    backgroundColor: "white",
  },
  icon: {
    width: metrix.VerticalSize(30),
    height: metrix.VerticalSize(30),
    resizeMode: "contain",
    tintColor: Colors.primary,
  },
  viewCon: {
    width: metrix.HorizontalSize(80),
    // backgroundColor: "#F6F6F6",
    borderRadius: metrix.VerticalSize(10),
    paddingBottom: metrix.VerticalSize(10),
    marginTop: metrix.VerticalSize(10),
    alignItems: "center",
    marginHorizontal: metrix.HorizontalSize(10),
  },
  Catimg: {
    resizeMode: "cover",
    width: metrix.HorizontalSize(80),
    height: metrix.VerticalSize(80),
  },
  circle: {
    width: metrix.VerticalSize(38),
    height: metrix.VerticalSize(38),
    borderRadius: metrix.VerticalSize(38 / 2),
    backgroundColor: Colors.primary,
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    opacity: 0.2,
    top: 0,
    right: 0,
    bottom: 0,
    left: metrix.HorizontalSize(0),
  },
  cartView: {
    width: metrix.VerticalSize(20),
    height: metrix.VerticalSize(20),
    borderRadius: metrix.VerticalSize(20 / 2),
    backgroundColor: Colors.BadgeRed,
    position: "absolute",
    top: metrix.VerticalSize(-2),
    right: metrix.HorizontalSize(-6),
    justifyContent: "center",
    alignItems: "center",
  },
  cartText: {
    fontSize: metrix.CustomFontSize(16),
    color: Colors.White,
    fontFamily: Fonts.IS,
  },
});
