const LOGIN = "LOGIN";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";

const SIGNUP = "SIGNUP";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_FAIL = "SIGNUP_FAIL";
export const GUEST_PHONE_NUMBER = "000";

const LOGOUT = "LOGOUT";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAIL = "LOGOUT_FAIL";
const REFRESH_USER_TOKEN = "REFRESH_USER_TOKEN";

const OPENMODAL = "OPENMODAL";
const TOGGLE_LOADER = "TOGGLE_LOADER";
const SET_LANG = "SET_LANG";
const GET_PROMOTIONS = "GET_PROMOTIONS";
const SET_PROMOTIONS = "SET_PROMOTIONS";
const SET_PRODUCTS = "SET_PRODUCTS";
const GET_MOSQUE = "GET_MOSQUE";
const GET_SUBSCRIPTIONS = "GET_SUBSCRIPTIONS";

const SET_ADDRESS = "SET_ADDRESS";
const SET_TERMS = "SET_TERMS";

const MERGE_CART = "MERGE_CART";
const SET_TOTAL = "SET_TOTAL";
const CLEAR_CART = "CLEAR_CART";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const SUBSCRIBE_PRODUCT = "SUBSCRIBE_PRODUCT";

const SET_USER_DATA = "SET_USER_DATA";
const UPDATE_USER_DATA = "UPDATE_USER_DATA";
const SET_AUTH = "SET_AUTH";
const MERGE_CART_PRODUCTS = "MERGE_CART_PRODUCTS";
const SET_CART_DATA = "SET_CART_DATA";

export {
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  GET_SUBSCRIPTIONS,
  SIGNUP,
  SIGNUP_SUCCESS,
  SIGNUP_FAIL,
  LOGOUT,
  LOGOUT_SUCCESS,
  LOGOUT_FAIL,
  OPENMODAL,
  GET_MOSQUE,
  SET_USER_DATA,
  SUBSCRIBE_PRODUCT,
  SET_LANG,
  GET_PROMOTIONS,
  MERGE_CART_PRODUCTS,
  SET_PROMOTIONS,
  SET_PRODUCTS,
  TOGGLE_LOADER,
  MERGE_CART,
  SET_ADDRESS,
  SET_TERMS,
  SET_TOTAL,
  CLEAR_CART,
  ADD_TO_CART,
  SET_CART_DATA,
  UPDATE_USER_DATA,
  REFRESH_USER_TOKEN,
};
