import { StyleSheet } from "react-native";
import metrix from "../../config/metrix";
import { Colors, Fonts } from "../../config/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.White,
    paddingHorizontal: metrix.HorizontalSize(18),
    paddingVertical: metrix.VerticalSize(25),
  },
  clearCart: {
    alignSelf: "flex-end",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: metrix.VerticalSize(10),
    borderWidth: 1,
    borderColor: Colors.primary,
    paddingVertical: metrix.VerticalSize(5),
    paddingHorizontal: metrix.HorizontalSize(8),
  },
  clearIcon: {
    tintColor: Colors.primary,
    width: metrix.VerticalSize(25),
    height: metrix.VerticalSize(25),
    marginLeft: metrix.HorizontalSize(5),
  },
  loaderContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.White,
  },
  image: {
    width: metrix.VerticalSize(400),
    height: metrix.VerticalSize(365),
    alignSelf: "center",
    marginTop: metrix.VerticalSize(65),
  },
  heading: {
    fontSize: metrix.CustomFontSize(24 + 2),
    marginTop: metrix.VerticalSize(26),
    marginBottom: metrix.VerticalSize(43),
    alignSelf: "center",
    fontFamily: Fonts.IM,
    color: Colors.primary,
  },
  button: {
    alignSelf: "center",
  },
  subHeading: {
    fontSize: metrix.CustomFontSize(20 + 2),
    marginBottom: metrix.VerticalSize(50),
    marginTop: metrix.VerticalSize(26),

    alignSelf: "center",
  },
  coverImage: {
    height: metrix.VerticalSize(300),
    width: "100%",
  },
  enterPromo: {
    color: Colors.primary,
    fontSize: metrix.CustomFontSize(14 + 2),
    textDecorationLine: "underline",
    fontFamily: Fonts.IM,
    marginVertical: metrix.VerticalSize(10),
    alignSelf: "flex-end",
  },
  modalHeading: {
    fontSize: metrix.CustomFontSize(18 + 2),
    fontFamily: Fonts.IR,
    marginHorizontal: metrix.HorizontalSize(5),
  },
  modalText: {
    fontSize: metrix.CustomFontSize(14 + 2),
    fontFamily: Fonts.IM,
    marginVertical: metrix.VerticalSize(10),
  },
  selectedPromoText: {
    fontSize: metrix.CustomFontSize(14 + 2),
    fontFamily: Fonts.IS,
    marginRight: metrix.HorizontalSize(5),
  },
  emptyText: {
    fontSize: metrix.CustomFontSize(18 + 2),
    fontFamily: Fonts.IM,
    textAlign: "center",
  },
  plus: {
    height: metrix.VerticalSize(24),
    width: metrix.VerticalSize(24),
    backgroundColor: "#E6E6E6",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: metrix.VerticalSize(12),
  },
  variationView: {
    width: metrix.HorizontalSize(325),
    height: metrix.VerticalSize(300),
    backgroundColor: Colors.White,
    borderRadius: metrix.VerticalSize(31),
    paddingVertical: metrix.VerticalSize(25),
    paddingHorizontal: metrix.HorizontalSize(25),
  },
  closeIcon: {
    width: metrix.HorizontalSize(20),
    height: metrix.VerticalSize(20),
  },

  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: metrix.VerticalSize(25),
  },
  QuantityViewRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: metrix.HorizontalSize(10),
    alignItems: "center",
  },
  QuantityContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: metrix.VerticalSize(10),
    width: metrix.HorizontalSize(70),
    justifyContent: "space-between",
  },
  plusminusIcon: {
    width: metrix.HorizontalSize(10),
    resizeMode: "contain",
    height: metrix.VerticalSize(10),
  },
  textContainer: {
    marginLeft: metrix.HorizontalSize(10),
    marginTop: metrix.VerticalSize(5),
  },
  productname: {
    color: Colors.text,
    marginBottom: metrix.VerticalSize(5),
    fontSize: metrix.CustomFontSize(13 + 2),
  },
  productprice: {
    color: Colors.text,
    opacity: 0.7,
    marginBottom: metrix.VerticalSize(5),

    fontSize: metrix.CustomFontSize(13 + 2),
  },
  productQuantity: {
    fontSize: metrix.CustomFontSize(13 + 2),
  },
  cartImage: {
    height: metrix.VerticalSize(100),
    width: metrix.HorizontalSize(100),
    resizeMode: "contain",
  },
  input: {
    borderWidth: metrix.VerticalSize(1),
    borderRadius: metrix.VerticalSize(5),
    height: metrix.VerticalSize(43),
    borderColor: Colors.LightGrey,
    paddingHorizontal: metrix.HorizontalSize(15),
  },
  box: {
    borderRadius: metrix.VerticalSize(5),
    padding: metrix.VerticalSize(10),
    // height: metrix.VerticalSize(43),
    backgroundColor: Colors.dullgrey,
  },
  arrowIcon: {
    height: metrix.VerticalSize(12),
    width: metrix.HorizontalSize(12),
  },
  bottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: metrix.VerticalSize(50),
  },
  buttonStyle: {},
  row: {
    flexDirection: "row",
    marginTop: metrix.VerticalSize(25),
  },
  printName: {
    position: "absolute",
    right: metrix.HorizontalSize(90),
    bottom: metrix.VerticalSize(70),
  },
  firstColumn: {
    flex: 1,
    marginRight: metrix.HorizontalSize(15),
  },
  secondColumn: {
    flex: 1,
  },
  cartSummaryView: {
    alignItems: "flex-end",
    marginTop: metrix.VerticalSize(15),
  },
  cartSummaryContainer: {
    flexDirection: "row",
    width: metrix.HorizontalSize(200),
    marginBottom: metrix.VerticalSize(15),
    justifyContent: "space-between",
  },
  iconContainer: {
    position: "absolute",
    top: metrix.VerticalSize(10),
    right: metrix.HorizontalSize(10),
  },
  font: {
    marginBottom: metrix.VerticalSize(10),
  },
  headingText: {
    textAlign: "center",
    marginVertical: metrix.VerticalSize(25),
    fontSize: metrix.CustomFontSize(18 + 2),
    fontFamily: Fonts.IM,
  },
  rowContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: metrix.VerticalSize(10),
  },
  circle: {
    width: metrix.VerticalSize(20),
    height: metrix.VerticalSize(20),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: metrix.VerticalSize(10),
    borderColor: Colors.primary,
    borderWidth: metrix.VerticalSize(2),
    marginRight: metrix.HorizontalSize(10),
  },
  innerCircle: {
    width: metrix.VerticalSize(10),
    height: metrix.VerticalSize(10),
    borderRadius: metrix.VerticalSize(5),
    backgroundColor: Colors.primary,
  },
  selectedPromo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: Colors.dullgrey,
    paddingVertical: metrix.VerticalSize(15),
    paddingHorizontal: metrix.HorizontalSize(15),
    borderRadius: metrix.VerticalSize(10),
  },
  cancelPromo: {
    flexDirection: "row",
    alignItems: "center",
  },
  totalBox: {
    backgroundColor: Colors.dullgrey,
    width: metrix.HorizontalSize(349),
    // height: metrix.VerticalSize(161),
    borderRadius: metrix.VerticalSize(5),
    alignSelf: "flex-end",
    paddingVertical: metrix.VerticalSize(18),
    paddingHorizontal: metrix.HorizontalSize(18),
    // marginTop: metrix.VerticalSize(15),
  },
  totalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: metrix.VerticalSize(16),
    marginBottom: metrix.VerticalSize(85),
    marginHorizontal: metrix.HorizontalSize(10),
  },
  totalTextRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  totalText: {
    fontSize: metrix.CustomFontSize(16 + 2),
    fontFamily: Fonts.IR,
    marginBottom: metrix.VerticalSize(12),
  },
  totalTextVal: {
    fontSize: metrix.CustomFontSize(16 + 2),
    fontFamily: Fonts.IS,
    marginLeft: metrix.HorizontalSize(35),
    marginBottom: metrix.VerticalSize(12),
  },
  total: {
    fontSize: metrix.CustomFontSize(18 + 2),
    fontFamily: Fonts.IR,
    color: Colors.primary,
  },
  freeText: {
    fontSize: metrix.CustomFontSize(16 + 2),
    fontFamily: Fonts.IR,
    color: Colors.primary,
    alignSelf: "flex-end",
    marginTop: metrix.VerticalSize(10),
  },
  warningModalView: {
    width: metrix.HorizontalSize(300),
    height: metrix.VerticalSize(230),
    backgroundColor: Colors.White,
    borderRadius: metrix.VerticalSize(10),
    paddingVertical: metrix.VerticalSize(25),
    paddingHorizontal: metrix.HorizontalSize(35),
    shadowColor: "#000",
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 5,
    alignItems: "center",
    justifyContent: "center",
  },
});
