import { StyleSheet } from "react-native";
import { Colors, Fonts } from "../../config/theme";
import metrix from "../../config/metrix";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.White,
    flex: 1,
    // paddingBottom: metrix.VerticalSize(40),
  },
  optionsBox: {
    // height: metrix.VerticalSize(121),
    width: metrix.HorizontalSize(121),
    backgroundColor: Colors.White,
    position: "absolute",
    right: metrix.HorizontalSize(11),
    top: metrix.VerticalSize(60),
    zIndex: 200,
    paddingVertical: metrix.VerticalSize(5),
  },
  closeIcon: {
    alignSelf: "flex-end",
  },
  rowContainer: {
    flexDirection: "row",
    marginBottom: metrix.VerticalSize(20),
  },
  circle: {
    width: metrix.VerticalSize(20),
    height: metrix.VerticalSize(20),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: metrix.VerticalSize(10),
    borderColor: Colors.primary,
    borderWidth: metrix.VerticalSize(2),
  },
  modalHeading: {
    fontSize: metrix.CustomFontSize(20 + 2),
    color: Colors.primary,
    textAlign: "center",
    marginTop: metrix.VerticalSize(3),
    marginBottom: metrix.VerticalSize(25),
  },
  paymentText: {
    textAlign: "left",
    marginLeft: metrix.HorizontalSize(20),
    fontSize: metrix.CustomFontSize(14 + 2),
    color: "#878889",
  },
  innerCircle: {
    width: metrix.VerticalSize(10),
    height: metrix.VerticalSize(10),
    borderRadius: metrix.VerticalSize(5),
    backgroundColor: Colors.primary,
  },
  modalBtn: {
    alignSelf: "center",
  },
  modalView: {
    width: metrix.HorizontalSize(365),
    height: metrix.VerticalSize(384),
    backgroundColor: Colors.White,
    borderRadius: metrix.VerticalSize(10),
    paddingVertical: metrix.VerticalSize(25),
    paddingHorizontal: metrix.HorizontalSize(35),
    shadowColor: "#000",
    shadowOpacity: 0.4,
    shadowRadius: 15,
  },
  cardImg: {
    width: metrix.VerticalSize(65),
    height: metrix.VerticalSize(65),
    marginRight: metrix.HorizontalSize(16),
  },
  imageRow: {
    flexDirection: "row",
    marginTop: metrix.VerticalSize(12),
  },
  tabView: {
    borderRadius: metrix.VerticalSize(80),
    borderWidth: metrix.VerticalSize(2),
    borderColor: Colors.primary,
    flexDirection: "row",
    marginTop: metrix.VerticalSize(21),
    alignSelf: "center",
  },
  boxText: {
    fontSize: metrix.CustomFontSize(14 + 2),
    fontFamily: Fonts.IR,
    paddingHorizontal: metrix.HorizontalSize(10),
    color: Colors.primary,
    paddingVertical: metrix.VerticalSize(10),
  },
  tabText: {
    fontSize: metrix.CustomFontSize(15 + 2),
    fontFamily: Fonts.IS,
    color: Colors.primary,
  },
  tab1: {
    width: metrix.HorizontalSize(275 / 2),
    height: metrix.VerticalSize(43),
    justifyContent: "center",
    alignItems: "center",
    borderLeftColor: Colors.primary,
    borderBottomColor: Colors.primary,
    borderTopColor: Colors.primary,
    borderTopLeftRadius: metrix.VerticalSize(80),
    borderTopRightRadius: metrix.VerticalSize(80),
    borderBottomLeftRadius: metrix.VerticalSize(80),
    borderBottomRightRadius: metrix.VerticalSize(80),
  },
  tab2: {
    width: metrix.HorizontalSize(275 / 2),
    height: metrix.VerticalSize(43),
    justifyContent: "center",
    alignItems: "center",
    borderRightColor: Colors.primary,
    borderBottomColor: Colors.primary,
    borderTopColor: Colors.primary,
    borderTopRightRadius: metrix.VerticalSize(80),
    borderTopLeftRadius: metrix.VerticalSize(80),
    borderBottomRightRadius: metrix.VerticalSize(80),
    borderBottomLeftRadius: metrix.VerticalSize(80),
  },
  dateText: {
    fontSize: metrix.CustomFontSize(18 + 2),
    fontFamily: Fonts.IR,
    color: Colors.text,
    marginBottom: metrix.VerticalSize(5),
  },
  icon: {
    width: metrix.HorizontalSize(15),
    height: metrix.HorizontalSize(15),
  },
  cardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  orderNoText: {
    fontSize: metrix.CustomFontSize(16 + 2),
    fontFamily: Fonts.IM,
    color: Colors.primary,
  },
  tabActive: {
    color: Colors.White,
  },
  listView: {
    paddingVertical: metrix.VerticalSize(23),
    paddingHorizontal: metrix.HorizontalSize(14),
  },
  listView2: {
    paddingBottom: metrix.VerticalSize(23),
    paddingHorizontal: metrix.HorizontalSize(14),
  },
  textRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  orderCard: {
    backgroundColor: Colors.textInputView,
    marginBottom: metrix.VerticalSize(17),
    borderRadius: metrix.VerticalSize(5),
    paddingVertical: metrix.VerticalSize(20),
    paddingHorizontal: metrix.HorizontalSize(20),
    // height: metrix.VerticalSize(221),
  },
  detailText: {
    width: metrix.HorizontalSize(190),
    lineHeight: metrix.VerticalSize(18),
    fontSize: metrix.CustomFontSize(14 + 2),
    fontFamily: Fonts.IR,
  },
  typeView: {
    flexDirection: "row",
    justifyContent: "center",
    justifyContent: "space-evenly",
    marginVertical: metrix.VerticalSize(20),
  },
  repeatText: {
    alignSelf: "center",
    fontSize: metrix.CustomFontSize(14 + 2),
    color: Colors.completedText,
    marginVertical: metrix.VerticalSize(15),
  },
});
